USE hr;
SELECT * FROM countries;
SELECT * FROM departments;
SELECT * FROM employees;
SELECT * FROM job_history;
SELECT * FROM jobs;
SELECT * FROM locations;
SELECT * FROM regions;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MAX(SALARY) FROM employees;

SELECT MAX(SALARY) - MIN(SALARY) FROM employees;

SELECT JOB_ID, AVG(SALARY) AS 'average_salary'
FROM employees
GROUP BY JOB_ID
ORDER BY 'average_salary' DESC;

SELECT SUM(SALARY) FROM employees;

SELECT MAX(SALARY), MIN(SALARY), SUM(SALARY), ROUND(AVG(SALARY), 2) 
FROM employees;

SELECT JOB_ID, COUNT(*) AS 'TOTAL' 
FROM employees
WHERE JOB_ID = 'IT_PROG';

SELECT JOB_ID, SUM(SALARY) FROM employees
GROUP BY JOB_ID;

SELECT JOB_ID, SUM(SALARY) FROM employees
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';

SELECT JOB_ID, AVG(SALARY) AS 'average_salary'
FROM employees
WHERE JOB_ID <> 'IT_PROG'
GROUP BY JOB_ID
ORDER BY `average_salary` DESC;

SELECT DEPARTMENT_ID, AVG(SALARY) AS 'average_salary', COUNT(*) AS 'number_of_employees'
FROM employees
GROUP BY DEPARTMENT_ID
HAVING number_of_employees > 10;

SET SQL_SAFE_UPDATES = 0;

UPDATE employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777')
WHERE PHONE_NUMBER LIKE '515%';

SELECT * FROM employees
WHERE LENGTH(FIRST_NAME) >= 8;

SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) AS HIRE_YEAR
FROM employees;

SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) AS HIRE_DAY
FROM employees;

SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) AS HIRE_MONTH
FROM employees;

SELECT UCASE(CONCAT(FIRST_NAME, ' ', LAST_NAME)) 
-- ou SELECT UPPER(CONCAT(FIRST_NAME, ' ', LAST_NAME)) 
FROM employees;

SELECT LAST_NAME, HIRE_DATE FROM employees
WHERE HIRE_DATE LIKE '1987-07%';
-- ou WHERE HIRE_DATE  BETWEEN '1987-07-01'  AND '1987-07-31';
-- ou WHERE MONTH(HIRE_DATE)=7 and YEAR(HIRE_DATE)=1987;

SELECT FIRST_NAME,
	LAST_NAME,
    DATEDIFF(CURRENT_DATE(), HIRE_DATE) AS 'DAYS_WORKED'
FROM employees;